### ISSUE TITLE
API .remove() command doesn't work if player has no sources defined

### ISSUE THREAD

**Issue by gusbmello** [AirenSoft/OvenPlayer#190] opened 2021-05-28 18:00 UTC
To reproduce the issue:

1. Go to https://ovenplayer.com/docs/demo.html (you should have a player with three sources)
![image](https://user-images.githubusercontent.com/12779243/120023765-a94fb300-bfc4-11eb-83bc-e761fd3c9cc0.png)

2. Run the following commands on the browser console:
`players = window.OvenPlayer.getPlayerList()` <- Store players loaded
`players[0].remove()` <- Remove the player (the page should look like the image below)
![image](https://user-images.githubusercontent.com/12779243/120023722-9a690080-bfc4-11eb-989c-37450e14f093.png)
`window.OvenPlayer.create("player", {
    mute: true
});` <- Create another player instance
`players = window.OvenPlayer.getPlayerList()` -> Store players loaded again
`players[0].remove()` -> Try to remove it

**Comment by SangwonOh** [comment] 2021-05-31 07:12
@gusbmello Processing is not smooth when OvenPlayer is created as an empty source. If a player is created with an empty source or a specified source, it seems that load and remove processing should be done neatly in each. Thanks for the report and I will fix it soon.

**Comment by gusbmello** [comment] 2021-06-21 14:31
@SangwonOh Thanks! It is now working as intended.

**Comment by gusbmello** [comment] 2021-06-21 15:17
Hi again, I noticed that when there's no sources defined the 'ready' event is not called, would that be the expected behavior?

**Comment by SangwonOh** [comment] 2021-06-22 07:24
@gusbmello Hi. Yes. That's the intended behavior. Since the ready state is a state in which playback is possible, if there is no playback source, the ready event does not occur. Thanks.

**Comment by SangwonOh** [comment] 2021-06-22 16:22
@gusbmello I've confirmed that the 'ready' event is never triggered if the playback source is not set on initialization. I think we need to change our policy.

**Comment by SangwonOh** [comment] 2021-09-03 13:57
@gusbmello Since OvenPlayer v0.10.2,  regardless of the source settings, the ready event is fired once when the player is initialized.

**Comment by SangwonOh** [comment] 2022-02-25 07:51
Consider it resolved and close the issue. Please reopen for further discussion.

**Closed by SangwonOh** 2022-02-25 07:51 UTC
