### ISSUE TITLE
showControl does not working

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenPlayer#239] opened 2021-12-07 15:32 UTC
hi there,
showControls on 0.10.12 version does not working, Ihave the next script

```
 <div id="player"></div>
    <script>
      var errorRetryTimer = null;
      var sources=[
                        {
                        "file": "wss://<?php echo $servers[$server]?>:3334/endir/stream/",
                        "type": "webrtc",
                        "label": "1. WebRtc"
                        },                                             {
                        "file": "https://<?php echo $servers[$server]?>:4443/endir/stream/playlist.m3u8",
                        "type": "hls",
                        "label":"5. Hls"
                        },
                        {
                        "file": "wss://<?php echo $servers[$server]?>:3334/endir/stream?transport=tcp",
                        "type": "webrtc",
                        "label": "2. Tcp" 
                        },
                        {
                        "file": "https://<?php echo $servers[$server]?>:4443/endir/stream/manifest.mpd",
                        "type": "dash",
                        "label":"4. Dash"
                        },                                                       
                    ];
    
      var player = OvenPlayer.create("player",
                {
                    sources: sources,
                    mute:true,
                    controls: false,
                    showBigPlayButton: false,
                    autoStart: true,
                    systemText : [
                        {
                        "lang" : "en",
                        "ui" :
                            {
                            "controls" : {
                                "live" : "En Directo",
                                "low_latency_live" : "En Directo",
                                "low_latency_p2p" : "Baja latencia en tiempo real p2p",
                            },
                            "playlist" : "Reproducción",
                                "setting" : {
                                    "title" : "Ajustes",
                                    "speed" : "Velocidad",
                                    "source" : "Fuente",
                                    "quality" : "Calidad",
                                    "caption" : "Leyenda",
                                    "display" : "Mostrar"
                                }
                            },
                    }]
                });
    player.on("stateChanged",function(e){
      if (player.getState() === "playing" || player.getState() === "paused"){
        player.showControls(true);
      }
    });
    player.showControls(true); //i add out of if to see if works but does not
    </script>
```

or maybe im doing somthing wrong, but it was working on 0.10.5 version (the one that i move from)

**Comment by SangwonOh** [comment] 2021-12-14 05:27
@alnux Hi. I found that showControls() doesn't work when "controls: false" is set in the player options. 

If you remove "controls: false" in the player options and hide the controls with "showControls(false)" in the "ready" event, it will work.

```javascript
player.on('ready', function () {
    player.showControls(false);
})

Even if "controls: false" is set in the player option, it seems that the showControls API needs to be modified so that it works well.

**Comment by alnux** [comment] 2021-12-15 04:37
Ok, bit as i told it was working good on 0.10.5 version

**Comment by SangwonOh** [comment] 2021-12-28 06:22
@alnux The `controls: false` option was malfunctioning. Fixed in version 0.10.13. Thanks.

**Comment by alnux** [comment] 2021-12-28 20:37
hi @SangwonOh all is nice buuuuut on iphone (ios 14.8.1)devices the showControl does not Work, this is the function

```
player.on("stateChanged",function(e){
      if (player.getState() === "playing" || player.getState() === "paused"){
        player.showControls(true);
      }
    });
```

**Comment by SangwonOh** [comment] 2021-12-31 06:15
It was confirmed that it works normally in iPhone Safari 14.4 and 15.1 versions. An older version of OvenPlayer may be running due to browser cache.

Thank you

**Comment by SangwonOh** [comment] 2022-02-25 09:06
Consider it resolved and close the issue. Please reopen for further discussion.

**Closed by SangwonOh** 2022-02-25 09:06 UTC
